In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
a = torch.tensor([[1,3,4,5],
                  [9,8,6,2],
                  [10,11,3,2]])
print(a.shape)
print(a.ndim)
print(a.nelement())

torch.Size([3, 4])
2
12


In [7]:
b = torch.tensor([[[1,2,4],
                   [3,6,5]],
                   [[8,4,2],
                    [9,4,3]]
                    ])
print(b.shape)
print(b.ndim)

torch.Size([2, 2, 3])
3


In [16]:
c = torch.zeros(10,7)
b = torch.rand(7)
print(f'------{c.shape}------\n ------{b.shape}-------\n')
c + b


------torch.Size([10, 7])------
 ------torch.Size([7])-------



tensor([[0.0688, 0.2332, 0.5680, 0.8508, 0.8073, 0.6217, 0.1648],
        [0.0688, 0.2332, 0.5680, 0.8508, 0.8073, 0.6217, 0.1648],
        [0.0688, 0.2332, 0.5680, 0.8508, 0.8073, 0.6217, 0.1648],
        [0.0688, 0.2332, 0.5680, 0.8508, 0.8073, 0.6217, 0.1648],
        [0.0688, 0.2332, 0.5680, 0.8508, 0.8073, 0.6217, 0.1648],
        [0.0688, 0.2332, 0.5680, 0.8508, 0.8073, 0.6217, 0.1648],
        [0.0688, 0.2332, 0.5680, 0.8508, 0.8073, 0.6217, 0.1648],
        [0.0688, 0.2332, 0.5680, 0.8508, 0.8073, 0.6217, 0.1648],
        [0.0688, 0.2332, 0.5680, 0.8508, 0.8073, 0.6217, 0.1648],
        [0.0688, 0.2332, 0.5680, 0.8508, 0.8073, 0.6217, 0.1648]])

In [17]:
c = torch.ones(4,2)
b = torch.rand(2)
c * b

tensor([[0.3790, 0.1875],
        [0.3790, 0.1875],
        [0.3790, 0.1875],
        [0.3790, 0.1875]])

In [20]:
a = torch.tensor([[1,2,3],
                  [4,5,6]])
b = torch.tensor([[1,1,1],
                  [2,2,2]]) 
a + b

tensor([[2, 3, 4],
        [6, 7, 8]])

In [21]:
a * b

tensor([[ 1,  2,  3],
        [ 8, 10, 12]])

In [23]:
c = torch.matmul(a,b.T)
d = a @ b.transpose(0,1)
print(f'{c} \n {d} ')


tensor([[ 6, 12],
        [15, 30]]) 
 tensor([[ 6, 12],
        [15, 30]]) 


In [27]:
a = torch.zeros(10,6)
print(a.view(2,5,6))
print(a.view(20,-1))

tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [28]:
a = torch.rand(3,5,6)
b = torch.rand(3,5,6)
print(a @ b)
# to show that i need to fit the last dim of the first tensor with the -2 dim of the second tensor

RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [3, 6] but got: [3, 5].

In [30]:
c = a @ b.transpose(-1,-2)
print(c.shape)

torch.Size([3, 5, 5])


In [34]:
a = torch.ones(3,10,2)
b = torch.rand(1,2)
a + b

tensor([[[1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001]],

        [[1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001]],

        [[1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001]]])

In [35]:
b = b.view(1,1,2)

In [36]:
a + b

tensor([[[1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001]],

        [[1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001]],

        [[1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001],
         [1.5860, 1.5001]]])

In [38]:
c = torch.zeros(4,3)
print(c.unsqueeze(0).shape)
print(c.squeeze(0).shape)

torch.Size([1, 4, 3])
torch.Size([4, 3])


In [40]:
a = torch.zeros(3,2,5,1)
print(a.permute(1,0,3,2).shape)

torch.Size([2, 3, 1, 5])
